spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/halouprogramer/spring-config-repository.git
          basedir: ~/tmp/github
server:
  port: 8002
